/**
 * Generated by orval 🍺
 * Do not edit manually.
 * tc-erp
 * Invoicing & ERP API for Portuguese SMEs
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { httpClient } from './http-client';
export interface UpdateAtCredentialsRequest {
  subuser?: string;
  password?: string;
}

export interface UpdateCompanyProfileRequest {
  nif?: string;
  legal_name?: string;
  /** @nullable */
  commercial_name?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  postal_code?: string | null;
  /** @nullable */
  city?: string | null;
  country?: string;
  /** @nullable */
  share_capital?: string | null;
  /** @nullable */
  registry_office?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  logo_key?: string | null;
  fiscal_region?: string;
  vat_regime?: string;
  cash_vat?: boolean;
}

export interface ChangePasswordRequest {
  current_password?: string;
  new_password?: string;
}

export interface RequestPasswordResetRequest {
  email?: string;
}

export interface ConfirmPasswordResetRequest {
  token?: string;
  new_password?: string;
}

export interface CreateCompanyRequest {
  nif?: string;
  legal_name?: string;
}

export interface InviteUserRequest {
  email?: string;
  name?: string;
  role?: string;
}

export interface ChangeMemberRoleRequest {
  role?: string;
}

export type GetUnitsList200ItemsItem = {
  code?: string;
  name?: string;
  decimals?: number;
};

export type GetUnitsList200 = {
  items?: GetUnitsList200ItemsItem[];
};

export type PostAtCredentialsTest200 = {
  valid?: boolean;
  /** @nullable */
  checked_at?: string | null;
  /** @nullable */
  error?: string | null;
};

export type GetCompanyProfileGet200 = {
  nif?: string;
  legal_name?: string;
  /** @nullable */
  commercial_name?: string | null;
  /** @nullable */
  address?: string | null;
  /** @nullable */
  postal_code?: string | null;
  /** @nullable */
  city?: string | null;
  country?: string;
  /** @nullable */
  share_capital?: string | null;
  /** @nullable */
  registry_office?: string | null;
  /** @nullable */
  email?: string | null;
  /** @nullable */
  phone?: string | null;
  /** @nullable */
  logo_key?: string | null;
  fiscal_region?: string;
  vat_regime?: string;
  cash_vat?: boolean;
};

export type GetDocumentTypesList200ItemsItem = {
  code?: string;
  saft_section?: string;
  signed?: boolean;
  stock_effect?: string;
  account_effect?: string;
  requires_at_prior_communication?: boolean;
};

export type GetDocumentTypesList200 = {
  items?: GetDocumentTypesList200ItemsItem[];
};

export type PostAuthLoginBody = {
  email?: string;
  password?: string;
};

export type PostAuthLogin200 = {
  authenticated?: boolean;
  must_change_password?: boolean;
};

export type GetCompaniesListMineParams = {
cursor?: string;
limit?: number;
};

export type GetCompaniesListMine200ItemsItem = {
  id?: string;
  nif?: string;
  legal_name?: string;
  role?: string;
};

export type GetCompaniesListMine200 = {
  items?: GetCompaniesListMine200ItemsItem[];
  /** @nullable */
  next_cursor?: string | null;
};

export type PostCompaniesCreate201 = {
  id?: string;
};

export type GetCompanyUsersList200ItemsItem = {
  user_id?: string;
  email?: string;
  name?: string;
  role?: string;
};

export type GetCompanyUsersList200 = {
  items?: GetCompanyUsersList200ItemsItem[];
};

export type GetMe200User = {
  id?: string;
  email?: string;
  name?: string;
  must_change_password?: boolean;
};

export type GetMe200CompaniesItem = {
  id?: string;
  legal_name?: string;
  role?: string;
  permissions?: string[];
};

export type GetMe200 = {
  user?: GetMe200User;
  companies?: GetMe200CompaniesItem[];
};

export type GetCountriesList200ItemsItem = {
  /** ISO 3166-1 alpha-2 */
  code?: string;
  name?: string;
};

export type GetCountriesList200 = {
  items?: GetCountriesList200ItemsItem[];
};

export type GetExemptionReasonsListParams = {
/**
 * Only reasons valid on this date; omit to list every reason ever seeded.
 */
as_of?: string;
};

export type GetExemptionReasonsList200ItemsItem = {
  code?: string;
  description?: string;
  legal_reference?: string;
  valid_from?: string;
  /** @nullable */
  valid_to?: string | null;
};

export type GetExemptionReasonsList200 = {
  items?: GetExemptionReasonsList200ItemsItem[];
};

export type GetTaxRatesListParams = {
/**
 * PT|PT-AC|PT-MA
 */
region?: string;
/**
 * Only rates valid on this date; omit to list every rate ever seeded.
 */
as_of?: string;
};

export type GetTaxRatesList200ItemsItem = {
  id?: string;
  region?: string;
  code?: string;
  percentage?: string;
  valid_from?: string;
  /** @nullable */
  valid_to?: string | null;
  description?: string;
};

export type GetTaxRatesList200 = {
  items?: GetTaxRatesList200ItemsItem[];
};

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getGetUnitsListUrl = () => {




  return `/api/v1/units`
}

export const getUnitsList = async ( options?: RequestInit): Promise<GetUnitsList200> => {

  return httpClient<GetUnitsList200>(getGetUnitsListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetUnitsListQueryKey = () => {
    return [
    `/api/v1/units`
    ] as const;
    }


export const getGetUnitsListQueryOptions = <TData = Awaited<ReturnType<typeof getUnitsList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnitsList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetUnitsListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUnitsList>>> = ({ signal }) => getUnitsList({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getUnitsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetUnitsListQueryResult = NonNullable<Awaited<ReturnType<typeof getUnitsList>>>
export type GetUnitsListQueryError = unknown


export function useGetUnitsList<TData = Awaited<ReturnType<typeof getUnitsList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnitsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUnitsList>>,
          TError,
          Awaited<ReturnType<typeof getUnitsList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUnitsList<TData = Awaited<ReturnType<typeof getUnitsList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnitsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUnitsList>>,
          TError,
          Awaited<ReturnType<typeof getUnitsList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetUnitsList<TData = Awaited<ReturnType<typeof getUnitsList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnitsList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetUnitsList<TData = Awaited<ReturnType<typeof getUnitsList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getUnitsList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetUnitsListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getPutAtCredentialsUpdateUrl = (companyId: string,) => {




  return `/api/v1/companies/${companyId}/at-credentials`
}

export const putAtCredentialsUpdate = async (companyId: string,
    updateAtCredentialsRequest: UpdateAtCredentialsRequest, options?: RequestInit): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return httpClient<void>(getPutAtCredentialsUpdateUrl(companyId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateAtCredentialsRequest)
  }
);}





export const getPutAtCredentialsUpdateMutationKey = () => ['putAtCredentialsUpdate'] as const;

export const getPutAtCredentialsUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAtCredentialsUpdate>>, TError,PutAtCredentialsUpdateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putAtCredentialsUpdate>>, TError,PutAtCredentialsUpdateMutationVariables, TContext> => {

const mutationKey = getPutAtCredentialsUpdateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putAtCredentialsUpdate>>, PutAtCredentialsUpdateMutationVariables> = (props) => {
          const {companyId,data} = props ?? {};

          return  putAtCredentialsUpdate(companyId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutAtCredentialsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof putAtCredentialsUpdate>>>
    export type PutAtCredentialsUpdateMutationBody = UpdateAtCredentialsRequest
    export type PutAtCredentialsUpdateMutationError = void
    export type PutAtCredentialsUpdateMutationVariables = {companyId: string;data: UpdateAtCredentialsRequest}

    export const usePutAtCredentialsUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putAtCredentialsUpdate>>, TError,PutAtCredentialsUpdateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putAtCredentialsUpdate>>,
        TError,
        PutAtCredentialsUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getPutAtCredentialsUpdateMutationOptions(options), queryClient);
    }

export const getPostAtCredentialsTestUrl = (companyId: string,) => {




  return `/api/v1/companies/${companyId}/at-credentials/test`
}

export const postAtCredentialsTest = async (companyId: string, options?: RequestInit): Promise<PostAtCredentialsTest200> => {

  return httpClient<PostAtCredentialsTest200>(getPostAtCredentialsTestUrl(companyId),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostAtCredentialsTestMutationKey = () => ['postAtCredentialsTest'] as const;

export const getPostAtCredentialsTestMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAtCredentialsTest>>, TError,PostAtCredentialsTestMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAtCredentialsTest>>, TError,PostAtCredentialsTestMutationVariables, TContext> => {

const mutationKey = getPostAtCredentialsTestMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAtCredentialsTest>>, PostAtCredentialsTestMutationVariables> = (props) => {
          const {companyId} = props ?? {};

          return  postAtCredentialsTest(companyId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAtCredentialsTestMutationResult = NonNullable<Awaited<ReturnType<typeof postAtCredentialsTest>>>

    export type PostAtCredentialsTestMutationError = void
    export type PostAtCredentialsTestMutationVariables = {companyId: string}

    export const usePostAtCredentialsTest = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAtCredentialsTest>>, TError,PostAtCredentialsTestMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAtCredentialsTest>>,
        TError,
        PostAtCredentialsTestMutationVariables,
        TContext
      > => {
      return useMutation(getPostAtCredentialsTestMutationOptions(options), queryClient);
    }

export const getGetCompanyProfileGetUrl = (companyId: string,) => {




  return `/api/v1/companies/${companyId}/profile`
}

export const getCompanyProfileGet = async (companyId: string, options?: RequestInit): Promise<GetCompanyProfileGet200> => {

  return httpClient<GetCompanyProfileGet200>(getGetCompanyProfileGetUrl(companyId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCompanyProfileGetQueryKey = (companyId: string,) => {
    return [
    `/api/v1/companies/${companyId}/profile`
    ] as const;
    }


export const getGetCompanyProfileGetQueryOptions = <TData = Awaited<ReturnType<typeof getCompanyProfileGet>>, TError = unknown>(companyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyProfileGet>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCompanyProfileGetQueryKey(companyId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompanyProfileGet>>> = ({ signal }) => getCompanyProfileGet(companyId, { signal });





   return  { queryKey, queryFn, enabled: companyId !== null && companyId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCompanyProfileGet>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCompanyProfileGetQueryResult = NonNullable<Awaited<ReturnType<typeof getCompanyProfileGet>>>
export type GetCompanyProfileGetQueryError = unknown


export function useGetCompanyProfileGet<TData = Awaited<ReturnType<typeof getCompanyProfileGet>>, TError = unknown>(
 companyId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyProfileGet>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanyProfileGet>>,
          TError,
          Awaited<ReturnType<typeof getCompanyProfileGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompanyProfileGet<TData = Awaited<ReturnType<typeof getCompanyProfileGet>>, TError = unknown>(
 companyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyProfileGet>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanyProfileGet>>,
          TError,
          Awaited<ReturnType<typeof getCompanyProfileGet>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompanyProfileGet<TData = Awaited<ReturnType<typeof getCompanyProfileGet>>, TError = unknown>(
 companyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyProfileGet>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCompanyProfileGet<TData = Awaited<ReturnType<typeof getCompanyProfileGet>>, TError = unknown>(
 companyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyProfileGet>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCompanyProfileGetQueryOptions(companyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getPutCompanyProfileUpdateUrl = (companyId: string,) => {




  return `/api/v1/companies/${companyId}/profile`
}

export const putCompanyProfileUpdate = async (companyId: string,
    updateCompanyProfileRequest: UpdateCompanyProfileRequest, options?: RequestInit): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return httpClient<void>(getPutCompanyProfileUpdateUrl(companyId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(updateCompanyProfileRequest)
  }
);}





export const getPutCompanyProfileUpdateMutationKey = () => ['putCompanyProfileUpdate'] as const;

export const getPutCompanyProfileUpdateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putCompanyProfileUpdate>>, TError,PutCompanyProfileUpdateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putCompanyProfileUpdate>>, TError,PutCompanyProfileUpdateMutationVariables, TContext> => {

const mutationKey = getPutCompanyProfileUpdateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putCompanyProfileUpdate>>, PutCompanyProfileUpdateMutationVariables> = (props) => {
          const {companyId,data} = props ?? {};

          return  putCompanyProfileUpdate(companyId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutCompanyProfileUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof putCompanyProfileUpdate>>>
    export type PutCompanyProfileUpdateMutationBody = UpdateCompanyProfileRequest
    export type PutCompanyProfileUpdateMutationError = void
    export type PutCompanyProfileUpdateMutationVariables = {companyId: string;data: UpdateCompanyProfileRequest}

    export const usePutCompanyProfileUpdate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putCompanyProfileUpdate>>, TError,PutCompanyProfileUpdateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putCompanyProfileUpdate>>,
        TError,
        PutCompanyProfileUpdateMutationVariables,
        TContext
      > => {
      return useMutation(getPutCompanyProfileUpdateMutationOptions(options), queryClient);
    }

export const getGetDocumentTypesListUrl = () => {




  return `/api/v1/document-types`
}

export const getDocumentTypesList = async ( options?: RequestInit): Promise<GetDocumentTypesList200> => {

  return httpClient<GetDocumentTypesList200>(getGetDocumentTypesListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetDocumentTypesListQueryKey = () => {
    return [
    `/api/v1/document-types`
    ] as const;
    }


export const getGetDocumentTypesListQueryOptions = <TData = Awaited<ReturnType<typeof getDocumentTypesList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentTypesList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentTypesListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentTypesList>>> = ({ signal }) => getDocumentTypesList({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocumentTypesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentTypesListQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentTypesList>>>
export type GetDocumentTypesListQueryError = unknown


export function useGetDocumentTypesList<TData = Awaited<ReturnType<typeof getDocumentTypesList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentTypesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentTypesList>>,
          TError,
          Awaited<ReturnType<typeof getDocumentTypesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentTypesList<TData = Awaited<ReturnType<typeof getDocumentTypesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentTypesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentTypesList>>,
          TError,
          Awaited<ReturnType<typeof getDocumentTypesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentTypesList<TData = Awaited<ReturnType<typeof getDocumentTypesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentTypesList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetDocumentTypesList<TData = Awaited<ReturnType<typeof getDocumentTypesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentTypesList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocumentTypesListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getPostAuthLoginUrl = () => {




  return `/api/v1/auth/login`
}

/**
 * @summary Authenticates with email and password and starts a session cookie.
 */
export const postAuthLogin = async (postAuthLoginBody?: PostAuthLoginBody, options?: RequestInit): Promise<PostAuthLogin200> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return httpClient<PostAuthLogin200>(getPostAuthLoginUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(postAuthLoginBody)
  }
);}





export const getPostAuthLoginMutationKey = () => ['postAuthLogin'] as const;

export const getPostAuthLoginMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,PostAuthLoginMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,PostAuthLoginMutationVariables, TContext> => {

const mutationKey = getPostAuthLoginMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogin>>, PostAuthLoginMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postAuthLogin(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogin>>>
    export type PostAuthLoginMutationBody = PostAuthLoginBody | undefined
    export type PostAuthLoginMutationError = void
    export type PostAuthLoginMutationVariables = {data?: PostAuthLoginBody}

    /**
 * @summary Authenticates with email and password and starts a session cookie.
 */
export const usePostAuthLogin = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogin>>, TError,PostAuthLoginMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogin>>,
        TError,
        PostAuthLoginMutationVariables,
        TContext
      > => {
      return useMutation(getPostAuthLoginMutationOptions(options), queryClient);
    }

export const getPostAuthLogoutUrl = () => {




  return `/api/v1/auth/logout`
}

/**
 * @summary Ends the session.
 */
export const postAuthLogout = async ( options?: RequestInit): Promise<unknown> => {

  return httpClient<unknown>(getPostAuthLogoutUrl(),
  {
    ...options,
    method: 'POST'


  }
);}





export const getPostAuthLogoutMutationKey = () => ['postAuthLogout'] as const;

export const getPostAuthLogoutMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext> => {

const mutationKey = getPostAuthLogoutMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthLogout>>, void> = () => {


          return  postAuthLogout()
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthLogout>>>

    export type PostAuthLogoutMutationError = void


    /**
 * @summary Ends the session.
 */
export const usePostAuthLogout = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthLogout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthLogout>>,
        TError,
        void,
        TContext
      > => {
      return useMutation(getPostAuthLogoutMutationOptions(options), queryClient);
    }

export const getPostAuthChangePasswordUrl = () => {




  return `/api/v1/auth/change-password`
}

export const postAuthChangePassword = async (changePasswordRequest: ChangePasswordRequest, options?: RequestInit): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return httpClient<void>(getPostAuthChangePasswordUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(changePasswordRequest)
  }
);}





export const getPostAuthChangePasswordMutationKey = () => ['postAuthChangePassword'] as const;

export const getPostAuthChangePasswordMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthChangePassword>>, TError,PostAuthChangePasswordMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthChangePassword>>, TError,PostAuthChangePasswordMutationVariables, TContext> => {

const mutationKey = getPostAuthChangePasswordMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthChangePassword>>, PostAuthChangePasswordMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postAuthChangePassword(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthChangePasswordMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthChangePassword>>>
    export type PostAuthChangePasswordMutationBody = ChangePasswordRequest
    export type PostAuthChangePasswordMutationError = void
    export type PostAuthChangePasswordMutationVariables = {data: ChangePasswordRequest}

    export const usePostAuthChangePassword = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthChangePassword>>, TError,PostAuthChangePasswordMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthChangePassword>>,
        TError,
        PostAuthChangePasswordMutationVariables,
        TContext
      > => {
      return useMutation(getPostAuthChangePasswordMutationOptions(options), queryClient);
    }

export const getPostAuthRequestPasswordResetUrl = () => {




  return `/api/v1/auth/password/reset`
}

export const postAuthRequestPasswordReset = async (requestPasswordResetRequest: RequestPasswordResetRequest, options?: RequestInit): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return httpClient<void>(getPostAuthRequestPasswordResetUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(requestPasswordResetRequest)
  }
);}





export const getPostAuthRequestPasswordResetMutationKey = () => ['postAuthRequestPasswordReset'] as const;

export const getPostAuthRequestPasswordResetMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRequestPasswordReset>>, TError,PostAuthRequestPasswordResetMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthRequestPasswordReset>>, TError,PostAuthRequestPasswordResetMutationVariables, TContext> => {

const mutationKey = getPostAuthRequestPasswordResetMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthRequestPasswordReset>>, PostAuthRequestPasswordResetMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postAuthRequestPasswordReset(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthRequestPasswordResetMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthRequestPasswordReset>>>
    export type PostAuthRequestPasswordResetMutationBody = RequestPasswordResetRequest
    export type PostAuthRequestPasswordResetMutationError = unknown
    export type PostAuthRequestPasswordResetMutationVariables = {data: RequestPasswordResetRequest}

    export const usePostAuthRequestPasswordReset = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthRequestPasswordReset>>, TError,PostAuthRequestPasswordResetMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthRequestPasswordReset>>,
        TError,
        PostAuthRequestPasswordResetMutationVariables,
        TContext
      > => {
      return useMutation(getPostAuthRequestPasswordResetMutationOptions(options), queryClient);
    }

export const getPostAuthConfirmPasswordResetUrl = () => {




  return `/api/v1/auth/password/reset/confirm`
}

export const postAuthConfirmPasswordReset = async (confirmPasswordResetRequest: ConfirmPasswordResetRequest, options?: RequestInit): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return httpClient<void>(getPostAuthConfirmPasswordResetUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(confirmPasswordResetRequest)
  }
);}





export const getPostAuthConfirmPasswordResetMutationKey = () => ['postAuthConfirmPasswordReset'] as const;

export const getPostAuthConfirmPasswordResetMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthConfirmPasswordReset>>, TError,PostAuthConfirmPasswordResetMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAuthConfirmPasswordReset>>, TError,PostAuthConfirmPasswordResetMutationVariables, TContext> => {

const mutationKey = getPostAuthConfirmPasswordResetMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAuthConfirmPasswordReset>>, PostAuthConfirmPasswordResetMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postAuthConfirmPasswordReset(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostAuthConfirmPasswordResetMutationResult = NonNullable<Awaited<ReturnType<typeof postAuthConfirmPasswordReset>>>
    export type PostAuthConfirmPasswordResetMutationBody = ConfirmPasswordResetRequest
    export type PostAuthConfirmPasswordResetMutationError = void
    export type PostAuthConfirmPasswordResetMutationVariables = {data: ConfirmPasswordResetRequest}

    export const usePostAuthConfirmPasswordReset = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAuthConfirmPasswordReset>>, TError,PostAuthConfirmPasswordResetMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAuthConfirmPasswordReset>>,
        TError,
        PostAuthConfirmPasswordResetMutationVariables,
        TContext
      > => {
      return useMutation(getPostAuthConfirmPasswordResetMutationOptions(options), queryClient);
    }

export const getGetCompaniesListMineUrl = (params?: GetCompaniesListMineParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/companies?${stringifiedParams}` : `/api/v1/companies`
}

export const getCompaniesListMine = async (params?: GetCompaniesListMineParams, options?: RequestInit): Promise<GetCompaniesListMine200> => {

  return httpClient<GetCompaniesListMine200>(getGetCompaniesListMineUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCompaniesListMineQueryKey = (params?: GetCompaniesListMineParams,) => {
    return [
    `/api/v1/companies`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetCompaniesListMineQueryOptions = <TData = Awaited<ReturnType<typeof getCompaniesListMine>>, TError = unknown>(params?: GetCompaniesListMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompaniesListMine>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCompaniesListMineQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompaniesListMine>>> = ({ signal }) => getCompaniesListMine(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCompaniesListMine>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCompaniesListMineQueryResult = NonNullable<Awaited<ReturnType<typeof getCompaniesListMine>>>
export type GetCompaniesListMineQueryError = unknown


export function useGetCompaniesListMine<TData = Awaited<ReturnType<typeof getCompaniesListMine>>, TError = unknown>(
 params: undefined |  GetCompaniesListMineParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompaniesListMine>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompaniesListMine>>,
          TError,
          Awaited<ReturnType<typeof getCompaniesListMine>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompaniesListMine<TData = Awaited<ReturnType<typeof getCompaniesListMine>>, TError = unknown>(
 params?: GetCompaniesListMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompaniesListMine>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompaniesListMine>>,
          TError,
          Awaited<ReturnType<typeof getCompaniesListMine>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompaniesListMine<TData = Awaited<ReturnType<typeof getCompaniesListMine>>, TError = unknown>(
 params?: GetCompaniesListMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompaniesListMine>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCompaniesListMine<TData = Awaited<ReturnType<typeof getCompaniesListMine>>, TError = unknown>(
 params?: GetCompaniesListMineParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompaniesListMine>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCompaniesListMineQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getPostCompaniesCreateUrl = () => {




  return `/api/v1/companies`
}

export const postCompaniesCreate = async (createCompanyRequest: CreateCompanyRequest, options?: RequestInit): Promise<PostCompaniesCreate201> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return httpClient<PostCompaniesCreate201>(getPostCompaniesCreateUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(createCompanyRequest)
  }
);}





export const getPostCompaniesCreateMutationKey = () => ['postCompaniesCreate'] as const;

export const getPostCompaniesCreateMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCompaniesCreate>>, TError,PostCompaniesCreateMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postCompaniesCreate>>, TError,PostCompaniesCreateMutationVariables, TContext> => {

const mutationKey = getPostCompaniesCreateMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCompaniesCreate>>, PostCompaniesCreateMutationVariables> = (props) => {
          const {data} = props ?? {};

          return  postCompaniesCreate(data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostCompaniesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof postCompaniesCreate>>>
    export type PostCompaniesCreateMutationBody = CreateCompanyRequest
    export type PostCompaniesCreateMutationError = void
    export type PostCompaniesCreateMutationVariables = {data: CreateCompanyRequest}

    export const usePostCompaniesCreate = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCompaniesCreate>>, TError,PostCompaniesCreateMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postCompaniesCreate>>,
        TError,
        PostCompaniesCreateMutationVariables,
        TContext
      > => {
      return useMutation(getPostCompaniesCreateMutationOptions(options), queryClient);
    }

export const getGetCompanyUsersListUrl = (companyId: string,) => {




  return `/api/v1/companies/${companyId}/users`
}

export const getCompanyUsersList = async (companyId: string, options?: RequestInit): Promise<GetCompanyUsersList200> => {

  return httpClient<GetCompanyUsersList200>(getGetCompanyUsersListUrl(companyId),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCompanyUsersListQueryKey = (companyId: string,) => {
    return [
    `/api/v1/companies/${companyId}/users`
    ] as const;
    }


export const getGetCompanyUsersListQueryOptions = <TData = Awaited<ReturnType<typeof getCompanyUsersList>>, TError = void>(companyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyUsersList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCompanyUsersListQueryKey(companyId);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCompanyUsersList>>> = ({ signal }) => getCompanyUsersList(companyId, { signal });





   return  { queryKey, queryFn, enabled: companyId !== null && companyId !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCompanyUsersList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCompanyUsersListQueryResult = NonNullable<Awaited<ReturnType<typeof getCompanyUsersList>>>
export type GetCompanyUsersListQueryError = void


export function useGetCompanyUsersList<TData = Awaited<ReturnType<typeof getCompanyUsersList>>, TError = void>(
 companyId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyUsersList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanyUsersList>>,
          TError,
          Awaited<ReturnType<typeof getCompanyUsersList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompanyUsersList<TData = Awaited<ReturnType<typeof getCompanyUsersList>>, TError = void>(
 companyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyUsersList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCompanyUsersList>>,
          TError,
          Awaited<ReturnType<typeof getCompanyUsersList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCompanyUsersList<TData = Awaited<ReturnType<typeof getCompanyUsersList>>, TError = void>(
 companyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyUsersList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCompanyUsersList<TData = Awaited<ReturnType<typeof getCompanyUsersList>>, TError = void>(
 companyId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCompanyUsersList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCompanyUsersListQueryOptions(companyId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getPostCompanyUsersInviteUrl = (companyId: string,) => {




  return `/api/v1/companies/${companyId}/users`
}

export const postCompanyUsersInvite = async (companyId: string,
    inviteUserRequest: InviteUserRequest, options?: RequestInit): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return httpClient<void>(getPostCompanyUsersInviteUrl(companyId),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(inviteUserRequest)
  }
);}





export const getPostCompanyUsersInviteMutationKey = () => ['postCompanyUsersInvite'] as const;

export const getPostCompanyUsersInviteMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCompanyUsersInvite>>, TError,PostCompanyUsersInviteMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postCompanyUsersInvite>>, TError,PostCompanyUsersInviteMutationVariables, TContext> => {

const mutationKey = getPostCompanyUsersInviteMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postCompanyUsersInvite>>, PostCompanyUsersInviteMutationVariables> = (props) => {
          const {companyId,data} = props ?? {};

          return  postCompanyUsersInvite(companyId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PostCompanyUsersInviteMutationResult = NonNullable<Awaited<ReturnType<typeof postCompanyUsersInvite>>>
    export type PostCompanyUsersInviteMutationBody = InviteUserRequest
    export type PostCompanyUsersInviteMutationError = void
    export type PostCompanyUsersInviteMutationVariables = {companyId: string;data: InviteUserRequest}

    export const usePostCompanyUsersInvite = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postCompanyUsersInvite>>, TError,PostCompanyUsersInviteMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postCompanyUsersInvite>>,
        TError,
        PostCompanyUsersInviteMutationVariables,
        TContext
      > => {
      return useMutation(getPostCompanyUsersInviteMutationOptions(options), queryClient);
    }

export const getPutCompanyUsersChangeRoleUrl = (companyId: string,
    userId: string,) => {




  return `/api/v1/companies/${companyId}/users/${userId}`
}

export const putCompanyUsersChangeRole = async (companyId: string,
    userId: string,
    changeMemberRoleRequest: ChangeMemberRoleRequest, options?: RequestInit): Promise<void> => {

    const getHeaders = (h?: NonNullable<RequestInit['headers']>): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(h as Iterable<Iterable<string>>, (entry) => Array.from(entry) as [string, string]),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
return httpClient<void>(getPutCompanyUsersChangeRoleUrl(companyId,userId),
  {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(changeMemberRoleRequest)
  }
);}





export const getPutCompanyUsersChangeRoleMutationKey = () => ['putCompanyUsersChangeRole'] as const;

export const getPutCompanyUsersChangeRoleMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putCompanyUsersChangeRole>>, TError,PutCompanyUsersChangeRoleMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof putCompanyUsersChangeRole>>, TError,PutCompanyUsersChangeRoleMutationVariables, TContext> => {

const mutationKey = getPutCompanyUsersChangeRoleMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof putCompanyUsersChangeRole>>, PutCompanyUsersChangeRoleMutationVariables> = (props) => {
          const {companyId,userId,data} = props ?? {};

          return  putCompanyUsersChangeRole(companyId,userId,data,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type PutCompanyUsersChangeRoleMutationResult = NonNullable<Awaited<ReturnType<typeof putCompanyUsersChangeRole>>>
    export type PutCompanyUsersChangeRoleMutationBody = ChangeMemberRoleRequest
    export type PutCompanyUsersChangeRoleMutationError = void
    export type PutCompanyUsersChangeRoleMutationVariables = {companyId: string;userId: string;data: ChangeMemberRoleRequest}

    export const usePutCompanyUsersChangeRole = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof putCompanyUsersChangeRole>>, TError,PutCompanyUsersChangeRoleMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof putCompanyUsersChangeRole>>,
        TError,
        PutCompanyUsersChangeRoleMutationVariables,
        TContext
      > => {
      return useMutation(getPutCompanyUsersChangeRoleMutationOptions(options), queryClient);
    }

export const getDeleteCompanyUsersRemoveUrl = (companyId: string,
    userId: string,) => {




  return `/api/v1/companies/${companyId}/users/${userId}`
}

export const deleteCompanyUsersRemove = async (companyId: string,
    userId: string, options?: RequestInit): Promise<void> => {

  return httpClient<void>(getDeleteCompanyUsersRemoveUrl(companyId,userId),
  {
    ...options,
    method: 'DELETE'


  }
);}





export const getDeleteCompanyUsersRemoveMutationKey = () => ['deleteCompanyUsersRemove'] as const;

export const getDeleteCompanyUsersRemoveMutationOptions = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompanyUsersRemove>>, TError,DeleteCompanyUsersRemoveMutationVariables, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteCompanyUsersRemove>>, TError,DeleteCompanyUsersRemoveMutationVariables, TContext> => {

const mutationKey = getDeleteCompanyUsersRemoveMutationKey();
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteCompanyUsersRemove>>, DeleteCompanyUsersRemoveMutationVariables> = (props) => {
          const {companyId,userId} = props ?? {};

          return  deleteCompanyUsersRemove(companyId,userId,)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteCompanyUsersRemoveMutationResult = NonNullable<Awaited<ReturnType<typeof deleteCompanyUsersRemove>>>

    export type DeleteCompanyUsersRemoveMutationError = void
    export type DeleteCompanyUsersRemoveMutationVariables = {companyId: string;userId: string}

    export const useDeleteCompanyUsersRemove = <TError = void,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteCompanyUsersRemove>>, TError,DeleteCompanyUsersRemoveMutationVariables, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteCompanyUsersRemove>>,
        TError,
        DeleteCompanyUsersRemoveMutationVariables,
        TContext
      > => {
      return useMutation(getDeleteCompanyUsersRemoveMutationOptions(options), queryClient);
    }

export const getGetHealthUrl = () => {




  return `/api/v1/health`
}

export const getHealth = async ( options?: RequestInit): Promise<void> => {

  return httpClient<void>(getGetHealthUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetHealthQueryKey = () => {
    return [
    `/api/v1/health`
    ] as const;
    }


export const getGetHealthQueryOptions = <TData = Awaited<ReturnType<typeof getHealth>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetHealthQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getHealth>>> = ({ signal }) => getHealth({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetHealthQueryResult = NonNullable<Awaited<ReturnType<typeof getHealth>>>
export type GetHealthQueryError = void


export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getHealth>>,
          TError,
          Awaited<ReturnType<typeof getHealth>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetHealth<TData = Awaited<ReturnType<typeof getHealth>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getHealth>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetHealthQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetMeUrl = () => {




  return `/api/v1/me`
}

export const getMe = async ( options?: RequestInit): Promise<GetMe200> => {

  return httpClient<GetMe200>(getGetMeUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetMeQueryKey = () => {
    return [
    `/api/v1/me`
    ] as const;
    }


export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = void>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = void


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = void>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetCountriesListUrl = () => {




  return `/api/v1/countries`
}

export const getCountriesList = async ( options?: RequestInit): Promise<GetCountriesList200> => {

  return httpClient<GetCountriesList200>(getGetCountriesListUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetCountriesListQueryKey = () => {
    return [
    `/api/v1/countries`
    ] as const;
    }


export const getGetCountriesListQueryOptions = <TData = Awaited<ReturnType<typeof getCountriesList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountriesList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCountriesListQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCountriesList>>> = ({ signal }) => getCountriesList({ signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCountriesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCountriesListQueryResult = NonNullable<Awaited<ReturnType<typeof getCountriesList>>>
export type GetCountriesListQueryError = unknown


export function useGetCountriesList<TData = Awaited<ReturnType<typeof getCountriesList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountriesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCountriesList>>,
          TError,
          Awaited<ReturnType<typeof getCountriesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCountriesList<TData = Awaited<ReturnType<typeof getCountriesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountriesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCountriesList>>,
          TError,
          Awaited<ReturnType<typeof getCountriesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCountriesList<TData = Awaited<ReturnType<typeof getCountriesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountriesList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCountriesList<TData = Awaited<ReturnType<typeof getCountriesList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCountriesList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCountriesListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetExemptionReasonsListUrl = (params?: GetExemptionReasonsListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/exemption-reasons?${stringifiedParams}` : `/api/v1/exemption-reasons`
}

export const getExemptionReasonsList = async (params?: GetExemptionReasonsListParams, options?: RequestInit): Promise<GetExemptionReasonsList200> => {

  return httpClient<GetExemptionReasonsList200>(getGetExemptionReasonsListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetExemptionReasonsListQueryKey = (params?: GetExemptionReasonsListParams,) => {
    return [
    `/api/v1/exemption-reasons`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetExemptionReasonsListQueryOptions = <TData = Awaited<ReturnType<typeof getExemptionReasonsList>>, TError = void>(params?: GetExemptionReasonsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExemptionReasonsList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetExemptionReasonsListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getExemptionReasonsList>>> = ({ signal }) => getExemptionReasonsList(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getExemptionReasonsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetExemptionReasonsListQueryResult = NonNullable<Awaited<ReturnType<typeof getExemptionReasonsList>>>
export type GetExemptionReasonsListQueryError = void


export function useGetExemptionReasonsList<TData = Awaited<ReturnType<typeof getExemptionReasonsList>>, TError = void>(
 params: undefined |  GetExemptionReasonsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExemptionReasonsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExemptionReasonsList>>,
          TError,
          Awaited<ReturnType<typeof getExemptionReasonsList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExemptionReasonsList<TData = Awaited<ReturnType<typeof getExemptionReasonsList>>, TError = void>(
 params?: GetExemptionReasonsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExemptionReasonsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getExemptionReasonsList>>,
          TError,
          Awaited<ReturnType<typeof getExemptionReasonsList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetExemptionReasonsList<TData = Awaited<ReturnType<typeof getExemptionReasonsList>>, TError = void>(
 params?: GetExemptionReasonsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExemptionReasonsList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetExemptionReasonsList<TData = Awaited<ReturnType<typeof getExemptionReasonsList>>, TError = void>(
 params?: GetExemptionReasonsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getExemptionReasonsList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetExemptionReasonsListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}







export const getGetTaxRatesListUrl = (params?: GetTaxRatesListParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/tax-rates?${stringifiedParams}` : `/api/v1/tax-rates`
}

export const getTaxRatesList = async (params?: GetTaxRatesListParams, options?: RequestInit): Promise<GetTaxRatesList200> => {

  return httpClient<GetTaxRatesList200>(getGetTaxRatesListUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetTaxRatesListQueryKey = (params?: GetTaxRatesListParams,) => {
    return [
    `/api/v1/tax-rates`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetTaxRatesListQueryOptions = <TData = Awaited<ReturnType<typeof getTaxRatesList>>, TError = void>(params?: GetTaxRatesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaxRatesList>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTaxRatesListQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTaxRatesList>>> = ({ signal }) => getTaxRatesList(params, { signal });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTaxRatesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTaxRatesListQueryResult = NonNullable<Awaited<ReturnType<typeof getTaxRatesList>>>
export type GetTaxRatesListQueryError = void


export function useGetTaxRatesList<TData = Awaited<ReturnType<typeof getTaxRatesList>>, TError = void>(
 params: undefined |  GetTaxRatesListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaxRatesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaxRatesList>>,
          TError,
          Awaited<ReturnType<typeof getTaxRatesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaxRatesList<TData = Awaited<ReturnType<typeof getTaxRatesList>>, TError = void>(
 params?: GetTaxRatesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaxRatesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTaxRatesList>>,
          TError,
          Awaited<ReturnType<typeof getTaxRatesList>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTaxRatesList<TData = Awaited<ReturnType<typeof getTaxRatesList>>, TError = void>(
 params?: GetTaxRatesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaxRatesList>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTaxRatesList<TData = Awaited<ReturnType<typeof getTaxRatesList>>, TError = void>(
 params?: GetTaxRatesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTaxRatesList>>, TError, TData>>, }
 , queryClient?: QueryClient
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTaxRatesListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
