/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PasswordResetRouteImport } from './routes/password-reset'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated.change-password'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated.companies'
import { Route as AuthenticatedCCompanyIdRouteImport } from './routes/_authenticated.c.$companyId'
import { Route as AuthenticatedCCompanyIdIndexRouteImport } from './routes/_authenticated.c.$companyId.index'
import { Route as AuthenticatedCCompanyIdMembersRouteImport } from './routes/_authenticated.c.$companyId.members'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCCompanyIdRoute = AuthenticatedCCompanyIdRouteImport.update({
  id: '/c/$companyId',
  path: '/c/$companyId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCCompanyIdIndexRoute =
  AuthenticatedCCompanyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCCompanyIdRoute,
  } as any)
const AuthenticatedCCompanyIdMembersRoute =
  AuthenticatedCCompanyIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedCCompanyIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/password-reset': typeof PasswordResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/c/$companyId': typeof AuthenticatedCCompanyIdRouteWithChildren
  '/c/$companyId/members': typeof AuthenticatedCCompanyIdMembersRoute
  '/c/$companyId/': typeof AuthenticatedCCompanyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/password-reset': typeof PasswordResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/c/$companyId/members': typeof AuthenticatedCCompanyIdMembersRoute
  '/c/$companyId': typeof AuthenticatedCCompanyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/password-reset': typeof PasswordResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/c/$companyId': typeof AuthenticatedCCompanyIdRouteWithChildren
  '/_authenticated/c/$companyId/members': typeof AuthenticatedCCompanyIdMembersRoute
  '/_authenticated/c/$companyId/': typeof AuthenticatedCCompanyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/password-reset'
    | '/reset-password'
    | '/change-password'
    | '/companies'
    | '/c/$companyId'
    | '/c/$companyId/members'
    | '/c/$companyId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/password-reset'
    | '/reset-password'
    | '/change-password'
    | '/companies'
    | '/c/$companyId/members'
    | '/c/$companyId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/password-reset'
    | '/reset-password'
    | '/_authenticated/change-password'
    | '/_authenticated/companies'
    | '/_authenticated/c/$companyId'
    | '/_authenticated/c/$companyId/members'
    | '/_authenticated/c/$companyId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PasswordResetRoute: typeof PasswordResetRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset': {
      id: '/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/c/$companyId': {
      id: '/_authenticated/c/$companyId'
      path: '/c/$companyId'
      fullPath: '/c/$companyId'
      preLoaderRoute: typeof AuthenticatedCCompanyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/c/$companyId/': {
      id: '/_authenticated/c/$companyId/'
      path: '/'
      fullPath: '/c/$companyId/'
      preLoaderRoute: typeof AuthenticatedCCompanyIdIndexRouteImport
      parentRoute: typeof AuthenticatedCCompanyIdRoute
    }
    '/_authenticated/c/$companyId/members': {
      id: '/_authenticated/c/$companyId/members'
      path: '/members'
      fullPath: '/c/$companyId/members'
      preLoaderRoute: typeof AuthenticatedCCompanyIdMembersRouteImport
      parentRoute: typeof AuthenticatedCCompanyIdRoute
    }
  }
}

interface AuthenticatedCCompanyIdRouteChildren {
  AuthenticatedCCompanyIdMembersRoute: typeof AuthenticatedCCompanyIdMembersRoute
  AuthenticatedCCompanyIdIndexRoute: typeof AuthenticatedCCompanyIdIndexRoute
}

const AuthenticatedCCompanyIdRouteChildren: AuthenticatedCCompanyIdRouteChildren =
  {
    AuthenticatedCCompanyIdMembersRoute: AuthenticatedCCompanyIdMembersRoute,
    AuthenticatedCCompanyIdIndexRoute: AuthenticatedCCompanyIdIndexRoute,
  }

const AuthenticatedCCompanyIdRouteWithChildren =
  AuthenticatedCCompanyIdRoute._addFileChildren(
    AuthenticatedCCompanyIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedCCompanyIdRoute: typeof AuthenticatedCCompanyIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedCCompanyIdRoute: AuthenticatedCCompanyIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PasswordResetRoute: PasswordResetRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
