/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PasswordResetRouteImport } from './routes/password-reset'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated.change-password'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated.companies'
import { Route as AuthenticatedCCompanyIdRouteImport } from './routes/_authenticated.c.$companyId'
import { Route as AuthenticatedCCompanyIdIndexRouteImport } from './routes/_authenticated.c.$companyId.index'
import { Route as AuthenticatedCCompanyIdCustomersRouteImport } from './routes/_authenticated.c.$companyId.customers'
import { Route as AuthenticatedCCompanyIdMembersRouteImport } from './routes/_authenticated.c.$companyId.members'
import { Route as AuthenticatedCCompanyIdPriceListsRouteImport } from './routes/_authenticated.c.$companyId.price-lists'
import { Route as AuthenticatedCCompanyIdProductFamiliesRouteImport } from './routes/_authenticated.c.$companyId.product-families'
import { Route as AuthenticatedCCompanyIdProductsRouteImport } from './routes/_authenticated.c.$companyId.products'
import { Route as AuthenticatedCCompanyIdReferenceDataRouteImport } from './routes/_authenticated.c.$companyId.reference-data'
import { Route as AuthenticatedCCompanyIdSettingsRouteImport } from './routes/_authenticated.c.$companyId.settings'
import { Route as AuthenticatedCCompanyIdSuppliersRouteImport } from './routes/_authenticated.c.$companyId.suppliers'
import { Route as AuthenticatedCCompanyIdWarehousesRouteImport } from './routes/_authenticated.c.$companyId.warehouses'
import { Route as AuthenticatedCCompanyIdProductsIndexRouteImport } from './routes/_authenticated.c.$companyId.products.index'
import { Route as AuthenticatedCCompanyIdProductsProductIdRouteImport } from './routes/_authenticated.c.$companyId.products.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordResetRoute = PasswordResetRouteImport.update({
  id: '/password-reset',
  path: '/password-reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCCompanyIdRoute = AuthenticatedCCompanyIdRouteImport.update({
  id: '/c/$companyId',
  path: '/c/$companyId',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCCompanyIdIndexRoute =
  AuthenticatedCCompanyIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCCompanyIdRoute,
  } as any)
const AuthenticatedCCompanyIdCustomersRoute =
  AuthenticatedCCompanyIdCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedCCompanyIdRoute,
  } as any)
const AuthenticatedCCompanyIdMembersRoute =
  AuthenticatedCCompanyIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedCCompanyIdRoute,
  } as any)
const AuthenticatedCCompanyIdPriceListsRoute =
  AuthenticatedCCompanyIdPriceListsRouteImport.update({
    id: '/price-lists',
    path: '/price-lists',
    getParentRoute: () => AuthenticatedCCompanyIdRoute,
  } as any)
const AuthenticatedCCompanyIdProductFamiliesRoute =
  AuthenticatedCCompanyIdProductFamiliesRouteImport.update({
    id: '/product-families',
    path: '/product-families',
    getParentRoute: () => AuthenticatedCCompanyIdRoute,
  } as any)
const AuthenticatedCCompanyIdProductsRoute =
  AuthenticatedCCompanyIdProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedCCompanyIdRoute,
  } as any)
const AuthenticatedCCompanyIdReferenceDataRoute =
  AuthenticatedCCompanyIdReferenceDataRouteImport.update({
    id: '/reference-data',
    path: '/reference-data',
    getParentRoute: () => AuthenticatedCCompanyIdRoute,
  } as any)
const AuthenticatedCCompanyIdSettingsRoute =
  AuthenticatedCCompanyIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedCCompanyIdRoute,
  } as any)
const AuthenticatedCCompanyIdSuppliersRoute =
  AuthenticatedCCompanyIdSuppliersRouteImport.update({
    id: '/suppliers',
    path: '/suppliers',
    getParentRoute: () => AuthenticatedCCompanyIdRoute,
  } as any)
const AuthenticatedCCompanyIdWarehousesRoute =
  AuthenticatedCCompanyIdWarehousesRouteImport.update({
    id: '/warehouses',
    path: '/warehouses',
    getParentRoute: () => AuthenticatedCCompanyIdRoute,
  } as any)
const AuthenticatedCCompanyIdProductsIndexRoute =
  AuthenticatedCCompanyIdProductsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCCompanyIdProductsRoute,
  } as any)
const AuthenticatedCCompanyIdProductsProductIdRoute =
  AuthenticatedCCompanyIdProductsProductIdRouteImport.update({
    id: '/$productId',
    path: '/$productId',
    getParentRoute: () => AuthenticatedCCompanyIdProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/password-reset': typeof PasswordResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/c/$companyId': typeof AuthenticatedCCompanyIdRouteWithChildren
  '/c/$companyId/customers': typeof AuthenticatedCCompanyIdCustomersRoute
  '/c/$companyId/members': typeof AuthenticatedCCompanyIdMembersRoute
  '/c/$companyId/price-lists': typeof AuthenticatedCCompanyIdPriceListsRoute
  '/c/$companyId/product-families': typeof AuthenticatedCCompanyIdProductFamiliesRoute
  '/c/$companyId/products': typeof AuthenticatedCCompanyIdProductsRouteWithChildren
  '/c/$companyId/reference-data': typeof AuthenticatedCCompanyIdReferenceDataRoute
  '/c/$companyId/settings': typeof AuthenticatedCCompanyIdSettingsRoute
  '/c/$companyId/suppliers': typeof AuthenticatedCCompanyIdSuppliersRoute
  '/c/$companyId/warehouses': typeof AuthenticatedCCompanyIdWarehousesRoute
  '/c/$companyId/': typeof AuthenticatedCCompanyIdIndexRoute
  '/c/$companyId/products/$productId': typeof AuthenticatedCCompanyIdProductsProductIdRoute
  '/c/$companyId/products/': typeof AuthenticatedCCompanyIdProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/password-reset': typeof PasswordResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/c/$companyId/customers': typeof AuthenticatedCCompanyIdCustomersRoute
  '/c/$companyId/members': typeof AuthenticatedCCompanyIdMembersRoute
  '/c/$companyId/price-lists': typeof AuthenticatedCCompanyIdPriceListsRoute
  '/c/$companyId/product-families': typeof AuthenticatedCCompanyIdProductFamiliesRoute
  '/c/$companyId/reference-data': typeof AuthenticatedCCompanyIdReferenceDataRoute
  '/c/$companyId/settings': typeof AuthenticatedCCompanyIdSettingsRoute
  '/c/$companyId/suppliers': typeof AuthenticatedCCompanyIdSuppliersRoute
  '/c/$companyId/warehouses': typeof AuthenticatedCCompanyIdWarehousesRoute
  '/c/$companyId': typeof AuthenticatedCCompanyIdIndexRoute
  '/c/$companyId/products/$productId': typeof AuthenticatedCCompanyIdProductsProductIdRoute
  '/c/$companyId/products': typeof AuthenticatedCCompanyIdProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/password-reset': typeof PasswordResetRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/c/$companyId': typeof AuthenticatedCCompanyIdRouteWithChildren
  '/_authenticated/c/$companyId/customers': typeof AuthenticatedCCompanyIdCustomersRoute
  '/_authenticated/c/$companyId/members': typeof AuthenticatedCCompanyIdMembersRoute
  '/_authenticated/c/$companyId/price-lists': typeof AuthenticatedCCompanyIdPriceListsRoute
  '/_authenticated/c/$companyId/product-families': typeof AuthenticatedCCompanyIdProductFamiliesRoute
  '/_authenticated/c/$companyId/products': typeof AuthenticatedCCompanyIdProductsRouteWithChildren
  '/_authenticated/c/$companyId/reference-data': typeof AuthenticatedCCompanyIdReferenceDataRoute
  '/_authenticated/c/$companyId/settings': typeof AuthenticatedCCompanyIdSettingsRoute
  '/_authenticated/c/$companyId/suppliers': typeof AuthenticatedCCompanyIdSuppliersRoute
  '/_authenticated/c/$companyId/warehouses': typeof AuthenticatedCCompanyIdWarehousesRoute
  '/_authenticated/c/$companyId/': typeof AuthenticatedCCompanyIdIndexRoute
  '/_authenticated/c/$companyId/products/$productId': typeof AuthenticatedCCompanyIdProductsProductIdRoute
  '/_authenticated/c/$companyId/products/': typeof AuthenticatedCCompanyIdProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/password-reset'
    | '/reset-password'
    | '/change-password'
    | '/companies'
    | '/c/$companyId'
    | '/c/$companyId/customers'
    | '/c/$companyId/members'
    | '/c/$companyId/price-lists'
    | '/c/$companyId/product-families'
    | '/c/$companyId/products'
    | '/c/$companyId/reference-data'
    | '/c/$companyId/settings'
    | '/c/$companyId/suppliers'
    | '/c/$companyId/warehouses'
    | '/c/$companyId/'
    | '/c/$companyId/products/$productId'
    | '/c/$companyId/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/password-reset'
    | '/reset-password'
    | '/change-password'
    | '/companies'
    | '/c/$companyId/customers'
    | '/c/$companyId/members'
    | '/c/$companyId/price-lists'
    | '/c/$companyId/product-families'
    | '/c/$companyId/reference-data'
    | '/c/$companyId/settings'
    | '/c/$companyId/suppliers'
    | '/c/$companyId/warehouses'
    | '/c/$companyId'
    | '/c/$companyId/products/$productId'
    | '/c/$companyId/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/password-reset'
    | '/reset-password'
    | '/_authenticated/change-password'
    | '/_authenticated/companies'
    | '/_authenticated/c/$companyId'
    | '/_authenticated/c/$companyId/customers'
    | '/_authenticated/c/$companyId/members'
    | '/_authenticated/c/$companyId/price-lists'
    | '/_authenticated/c/$companyId/product-families'
    | '/_authenticated/c/$companyId/products'
    | '/_authenticated/c/$companyId/reference-data'
    | '/_authenticated/c/$companyId/settings'
    | '/_authenticated/c/$companyId/suppliers'
    | '/_authenticated/c/$companyId/warehouses'
    | '/_authenticated/c/$companyId/'
    | '/_authenticated/c/$companyId/products/$productId'
    | '/_authenticated/c/$companyId/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PasswordResetRoute: typeof PasswordResetRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-reset': {
      id: '/password-reset'
      path: '/password-reset'
      fullPath: '/password-reset'
      preLoaderRoute: typeof PasswordResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/c/$companyId': {
      id: '/_authenticated/c/$companyId'
      path: '/c/$companyId'
      fullPath: '/c/$companyId'
      preLoaderRoute: typeof AuthenticatedCCompanyIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/c/$companyId/': {
      id: '/_authenticated/c/$companyId/'
      path: '/'
      fullPath: '/c/$companyId/'
      preLoaderRoute: typeof AuthenticatedCCompanyIdIndexRouteImport
      parentRoute: typeof AuthenticatedCCompanyIdRoute
    }
    '/_authenticated/c/$companyId/customers': {
      id: '/_authenticated/c/$companyId/customers'
      path: '/customers'
      fullPath: '/c/$companyId/customers'
      preLoaderRoute: typeof AuthenticatedCCompanyIdCustomersRouteImport
      parentRoute: typeof AuthenticatedCCompanyIdRoute
    }
    '/_authenticated/c/$companyId/members': {
      id: '/_authenticated/c/$companyId/members'
      path: '/members'
      fullPath: '/c/$companyId/members'
      preLoaderRoute: typeof AuthenticatedCCompanyIdMembersRouteImport
      parentRoute: typeof AuthenticatedCCompanyIdRoute
    }
    '/_authenticated/c/$companyId/price-lists': {
      id: '/_authenticated/c/$companyId/price-lists'
      path: '/price-lists'
      fullPath: '/c/$companyId/price-lists'
      preLoaderRoute: typeof AuthenticatedCCompanyIdPriceListsRouteImport
      parentRoute: typeof AuthenticatedCCompanyIdRoute
    }
    '/_authenticated/c/$companyId/product-families': {
      id: '/_authenticated/c/$companyId/product-families'
      path: '/product-families'
      fullPath: '/c/$companyId/product-families'
      preLoaderRoute: typeof AuthenticatedCCompanyIdProductFamiliesRouteImport
      parentRoute: typeof AuthenticatedCCompanyIdRoute
    }
    '/_authenticated/c/$companyId/products': {
      id: '/_authenticated/c/$companyId/products'
      path: '/products'
      fullPath: '/c/$companyId/products'
      preLoaderRoute: typeof AuthenticatedCCompanyIdProductsRouteImport
      parentRoute: typeof AuthenticatedCCompanyIdRoute
    }
    '/_authenticated/c/$companyId/reference-data': {
      id: '/_authenticated/c/$companyId/reference-data'
      path: '/reference-data'
      fullPath: '/c/$companyId/reference-data'
      preLoaderRoute: typeof AuthenticatedCCompanyIdReferenceDataRouteImport
      parentRoute: typeof AuthenticatedCCompanyIdRoute
    }
    '/_authenticated/c/$companyId/settings': {
      id: '/_authenticated/c/$companyId/settings'
      path: '/settings'
      fullPath: '/c/$companyId/settings'
      preLoaderRoute: typeof AuthenticatedCCompanyIdSettingsRouteImport
      parentRoute: typeof AuthenticatedCCompanyIdRoute
    }
    '/_authenticated/c/$companyId/suppliers': {
      id: '/_authenticated/c/$companyId/suppliers'
      path: '/suppliers'
      fullPath: '/c/$companyId/suppliers'
      preLoaderRoute: typeof AuthenticatedCCompanyIdSuppliersRouteImport
      parentRoute: typeof AuthenticatedCCompanyIdRoute
    }
    '/_authenticated/c/$companyId/warehouses': {
      id: '/_authenticated/c/$companyId/warehouses'
      path: '/warehouses'
      fullPath: '/c/$companyId/warehouses'
      preLoaderRoute: typeof AuthenticatedCCompanyIdWarehousesRouteImport
      parentRoute: typeof AuthenticatedCCompanyIdRoute
    }
    '/_authenticated/c/$companyId/products/': {
      id: '/_authenticated/c/$companyId/products/'
      path: '/'
      fullPath: '/c/$companyId/products/'
      preLoaderRoute: typeof AuthenticatedCCompanyIdProductsIndexRouteImport
      parentRoute: typeof AuthenticatedCCompanyIdProductsRoute
    }
    '/_authenticated/c/$companyId/products/$productId': {
      id: '/_authenticated/c/$companyId/products/$productId'
      path: '/$productId'
      fullPath: '/c/$companyId/products/$productId'
      preLoaderRoute: typeof AuthenticatedCCompanyIdProductsProductIdRouteImport
      parentRoute: typeof AuthenticatedCCompanyIdProductsRoute
    }
  }
}

interface AuthenticatedCCompanyIdProductsRouteChildren {
  AuthenticatedCCompanyIdProductsProductIdRoute: typeof AuthenticatedCCompanyIdProductsProductIdRoute
  AuthenticatedCCompanyIdProductsIndexRoute: typeof AuthenticatedCCompanyIdProductsIndexRoute
}

const AuthenticatedCCompanyIdProductsRouteChildren: AuthenticatedCCompanyIdProductsRouteChildren =
  {
    AuthenticatedCCompanyIdProductsProductIdRoute:
      AuthenticatedCCompanyIdProductsProductIdRoute,
    AuthenticatedCCompanyIdProductsIndexRoute:
      AuthenticatedCCompanyIdProductsIndexRoute,
  }

const AuthenticatedCCompanyIdProductsRouteWithChildren =
  AuthenticatedCCompanyIdProductsRoute._addFileChildren(
    AuthenticatedCCompanyIdProductsRouteChildren,
  )

interface AuthenticatedCCompanyIdRouteChildren {
  AuthenticatedCCompanyIdCustomersRoute: typeof AuthenticatedCCompanyIdCustomersRoute
  AuthenticatedCCompanyIdMembersRoute: typeof AuthenticatedCCompanyIdMembersRoute
  AuthenticatedCCompanyIdPriceListsRoute: typeof AuthenticatedCCompanyIdPriceListsRoute
  AuthenticatedCCompanyIdProductFamiliesRoute: typeof AuthenticatedCCompanyIdProductFamiliesRoute
  AuthenticatedCCompanyIdProductsRoute: typeof AuthenticatedCCompanyIdProductsRouteWithChildren
  AuthenticatedCCompanyIdReferenceDataRoute: typeof AuthenticatedCCompanyIdReferenceDataRoute
  AuthenticatedCCompanyIdSettingsRoute: typeof AuthenticatedCCompanyIdSettingsRoute
  AuthenticatedCCompanyIdSuppliersRoute: typeof AuthenticatedCCompanyIdSuppliersRoute
  AuthenticatedCCompanyIdWarehousesRoute: typeof AuthenticatedCCompanyIdWarehousesRoute
  AuthenticatedCCompanyIdIndexRoute: typeof AuthenticatedCCompanyIdIndexRoute
}

const AuthenticatedCCompanyIdRouteChildren: AuthenticatedCCompanyIdRouteChildren =
  {
    AuthenticatedCCompanyIdCustomersRoute:
      AuthenticatedCCompanyIdCustomersRoute,
    AuthenticatedCCompanyIdMembersRoute: AuthenticatedCCompanyIdMembersRoute,
    AuthenticatedCCompanyIdPriceListsRoute:
      AuthenticatedCCompanyIdPriceListsRoute,
    AuthenticatedCCompanyIdProductFamiliesRoute:
      AuthenticatedCCompanyIdProductFamiliesRoute,
    AuthenticatedCCompanyIdProductsRoute:
      AuthenticatedCCompanyIdProductsRouteWithChildren,
    AuthenticatedCCompanyIdReferenceDataRoute:
      AuthenticatedCCompanyIdReferenceDataRoute,
    AuthenticatedCCompanyIdSettingsRoute: AuthenticatedCCompanyIdSettingsRoute,
    AuthenticatedCCompanyIdSuppliersRoute:
      AuthenticatedCCompanyIdSuppliersRoute,
    AuthenticatedCCompanyIdWarehousesRoute:
      AuthenticatedCCompanyIdWarehousesRoute,
    AuthenticatedCCompanyIdIndexRoute: AuthenticatedCCompanyIdIndexRoute,
  }

const AuthenticatedCCompanyIdRouteWithChildren =
  AuthenticatedCCompanyIdRoute._addFileChildren(
    AuthenticatedCCompanyIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedCCompanyIdRoute: typeof AuthenticatedCCompanyIdRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedCCompanyIdRoute: AuthenticatedCCompanyIdRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  PasswordResetRoute: PasswordResetRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
