import { defineConfig } from 'orval'

// Regenerated by `make openapi` (or `pnpm generate-client`) from
// api/openapi.json — never hand-edit src/api/generated.ts.
export default defineConfig({
  tcErp: {
    input: '../api/openapi.json',
    output: {
      target: 'src/api/generated.ts',
      client: 'react-query',
      httpClient: 'fetch',
      mode: 'single',
      mock: false,
      override: {
        mutator: {
          path: './src/api/http-client.ts',
          name: 'httpClient',
        },
        fetch: {
          // httpClient() returns the parsed body directly and throws
          // ApiError on a non-2xx response — not the {data, status,
          // headers} envelope orval's fetch client returns by default.
          includeHttpResponseReturnType: false,
        },
      },
    },
  },
})
